# Generated by Django 2.2.6 on 2019-10-23 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Email', models.CharField(max_length=255)),
                ('Phone', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=10000000)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTableDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=255)),
                ('Lname', models.CharField(max_length=255)),
                ('Mobile', models.CharField(max_length=255)),
                ('Country', models.CharField(blank=True, max_length=255)),
                ('State', models.CharField(blank=True, max_length=255)),
                ('City', models.CharField(blank=True, max_length=255)),
                ('Zip', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, max_length=10000000)),
                ('Vendor', models.BooleanField(default=True)),
                ('Pic', models.TextField(blank=True)),
                ('Complete', models.BooleanField(default=False)),
                ('ISConfirmed', models.BooleanField(default=False)),
                ('Activation_Key', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.States')),
            ],
        ),
    ]
