# Generated by Django 2.2.6 on 2019-10-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191023_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Vendor',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('S', 'Super'), ('U', 'User'), ('V', 'Vendor')], default='U', max_length=1),
        ),
    ]
