# Generated by Django 2.2.6 on 2019-11-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20191025_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='Mobile',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
