# Generated by Django 2.2.6 on 2019-11-05 05:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor', '0003_vendorstoreinformation_isdeleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0002_remove_sub_sub_categories_cat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductID', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Title', models.CharField(blank=True, max_length=255, null=True)),
                ('P_Des', models.CharField(blank=True, max_length=15000, null=True)),
                ('P_Condition', models.CharField(blank=True, max_length=255, null=True)),
                ('Active', models.BooleanField(default=False)),
                ('Sold', models.BooleanField(default=False)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('MaxQuantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Pic', models.TextField(blank=True, default='', null=True)),
                ('CreatedDate', models.DateTimeField(auto_now_add=True, null=True)),
                ('declineprice', models.IntegerField(blank=True, null=True)),
                ('DicountStatus', models.BooleanField(default=False)),
                ('Discountprice', models.IntegerField(blank=True, null=True)),
                ('Discountpersentage', models.FloatField(blank=True, null=True)),
                ('count_no', models.IntegerField(blank=True, default=0, null=True)),
                ('product_ad_active', models.BooleanField(default=False)),
                ('aproval', models.BooleanField(default=False)),
                ('Cat_Name', models.ForeignKey(blank=True, db_column='Cat_Name', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Main_Categories', to_field='Cat_Name')),
                ('StoreName', models.ForeignKey(blank=True, db_column='StoreName', null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor.VendorStoreInformation', to_field='StoreName')),
                ('Sub_Cat_Name', models.ForeignKey(blank=True, db_column='Sub_Cat_Name', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Sub_Categories', to_field='Sub_Cat_Name')),
                ('Sub_Sub_Cat_Name', models.ForeignKey(blank=True, db_column='Sub_Sub_Cat_Name', null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Sub_Sub_Categories', to_field='Sub_Sub_Cat_Name')),
                ('User_ID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
