# Generated by Django 2.2.6 on 2019-11-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='product',
            name='declineprice',
        ),
    ]
