# Generated by Django 2.2.6 on 2019-11-05 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20191105_0528'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductID',
        ),
    ]
