# Generated by Django 2.2.6 on 2019-11-05 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_productid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='count_no',
        ),
    ]
