# Generated by Django 2.2.6 on 2019-11-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_count_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='FixedPrice',
            field=models.IntegerField(blank=True, default=0, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
