# Generated by Django 2.2.6 on 2019-11-13 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20191111_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
        migrations.AlterField(
            model_name='product',
            name='Discountprice',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='FixedPrice',
            field=models.FloatField(blank=True, default=0, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='Jewelry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(blank=True, max_length=20000, null=True)),
                ('SKU', models.CharField(blank=True, max_length=20000, null=True)),
                ('MetalType', models.CharField(blank=True, max_length=20000, null=True)),
                ('MetalColor', models.CharField(blank=True, max_length=20000, null=True)),
                ('MoldKit', models.CharField(blank=True, max_length=20000, null=True)),
                ('TopBottom', models.CharField(blank=True, max_length=20000, null=True)),
                ('PC', models.CharField(blank=True, max_length=20000, null=True)),
                ('Size', models.IntegerField(blank=True, default=0, null=True)),
                ('ChainType', models.CharField(blank=True, max_length=20000, null=True)),
                ('Color', models.CharField(blank=True, max_length=20000, null=True)),
                ('Product_ID', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
        ),
    ]
