# Generated by Django 2.2.6 on 2019-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191113_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='Letter',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
