# Generated by Django 2.2.6 on 2019-11-14 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_jewelry_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelry',
            name='StoreName',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
