# Generated by Django 2.2.6 on 2019-11-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_jewelry_storename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jewelry',
            name='Size',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
