# Generated by Django 2.2.6 on 2019-11-04 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat_Name', models.CharField(max_length=255, unique=True)),
                ('Cat_Des', models.CharField(max_length=255)),
                ('Pic', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Cat_Name', models.CharField(max_length=255, unique=True)),
                ('Subcat_Des', models.CharField(max_length=255)),
                ('Pic', models.CharField(default='', max_length=255, null=True)),
                ('Cat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Main_Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Sub_Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sub_Sub_Cat_Name', models.CharField(max_length=255, unique=True)),
                ('Sub_Subcat_Des', models.CharField(max_length=255)),
                ('Pic', models.CharField(default='', max_length=255, null=True)),
                ('Cat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Main_Categories')),
                ('Sub_Cat_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.Sub_Categories')),
            ],
        ),
    ]
