# Generated by Django 2.2.6 on 2019-11-04 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_sub_categories',
            name='Cat_ID',
        ),
    ]
