# Generated by Django 2.2.6 on 2019-11-22 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20191118_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature_Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feature_Value', models.CharField(blank=True, max_length=200, null=True)),
                ('Feature_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Features')),
                ('Sub_Categories_Id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='category.Sub_Categories')),
            ],
        ),
        migrations.AddField(
            model_name='sub_categories',
            name='Feature',
            field=models.ManyToManyField(blank=True, null=True, to='category.Features'),
        ),
    ]
