# Generated by Django 2.2.6 on 2019-11-06 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistAndCart', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='product',
            new_name='ProductID',
        ),
        migrations.RenameField(
            model_name='checkout',
            old_name='user',
            new_name='User_ID',
        ),
    ]
