# Generated by Django 2.2.6 on 2019-11-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistAndCart', '0002_auto_20191106_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='CreatedDate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
