# Generated by Django 2.2.6 on 2019-11-07 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistAndCart', '0003_checkout_createddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discountcoupons',
            old_name='Qty',
            new_name='Quantity',
        ),
    ]
