# Generated by Django 2.2.6 on 2019-11-20 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watchlistAndCart', '0004_auto_20191107_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='watchlistAndCart.DiscountCoupons'),
        ),
    ]
